version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest" .
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:latest"
            fi
